"""
Pollinations.ai helper.

Flux (text-to-image, character reference sheets) is nominally free and
unlimited, but a confirmed live bug affects some Flux requests with
403/silent model-substitution under load (seen during testing: a reference
image came back generated by "sana", a different, lower-quality model, with
no error at all — Pollinations just served something else silently).
Sending the registered API key on Flux calls too, not just Kontext, reduces
this — authenticated requests appear to route more reliably than anonymous
ones. Register a free key at https://enter.pollinations.ai if you don't
have one; POLLINATIONS_API_KEY works for both functions in this file now.

Required environment variable (optional for Flux, required for Kontext):
  POLLINATIONS_API_KEY
"""
import os
import time
import requests

IMAGE_BASE = "https://image.pollinations.ai"
GEN_BASE = "https://gen.pollinations.ai"


def _get_with_retry(url: str, params: dict, headers: dict | None = None,
                     retries: int = 3, backoff: float = 5.0) -> bytes:
    last_err = None
    for attempt in range(retries):
        try:
            r = requests.get(url, params=params, headers=headers or {}, timeout=120)
            r.raise_for_status()
            if r.headers.get("content-type", "").startswith("image"):
                return r.content
            raise ValueError(f"Unexpected content-type: {r.headers.get('content-type')}, body: {r.text[:300]}")
        except requests.exceptions.HTTPError as e:
            body = e.response.text[:500] if e.response is not None else ""
            last_err = f"{e} | response body: {body}"
            time.sleep(backoff * (attempt + 1))
        except Exception as e:
            last_err = e
            time.sleep(backoff * (attempt + 1))
    raise RuntimeError(f"Pollinations (Flux) request failed after {retries} attempts: {last_err}")


DEFAULT_NEGATIVE_PROMPT = (
    "blurry, distorted, disfigured, deformed, extra limbs, extra fingers, "
    "missing fingers, bad anatomy, bad proportions, mutated hands, watermark, "
    "signature, text, low quality, low resolution, jpeg artifacts, grainy, "
    "duplicate, cropped, out of frame"
)


def generate_reference(prompt: str, seed: int, width: int = 1024, height: int = 1024,
                        negative_prompt: str = DEFAULT_NEGATIVE_PROMPT) -> bytes:
    api_key = os.environ.get("POLLINATIONS_API_KEY")
    quality_boost = "highly detailed, clean linework, professional character illustration, sharp focus"
    full_prompt = f"{prompt}. {quality_boost}"
    url = f"{IMAGE_BASE}/prompt/{requests.utils.quote(full_prompt)}"
    params = {
        "model": "flux", "seed": seed, "width": width, "height": height,
        "nologo": "true", "negative_prompt": negative_prompt,
    }
    headers = {"Authorization": f"Bearer {api_key}"} if api_key else None
    return _get_with_retry(url, params, headers=headers)


def edit_scene(reference_image_bytes: bytes, scene_prompt: str, seed: int,
                retries: int = 3, backoff: float = 5.0) -> bytes:
    api_key = os.environ.get("POLLINATIONS_API_KEY")
    if not api_key:
        raise RuntimeError(
            "POLLINATIONS_API_KEY not set. Register a free secret key at "
            "https://enter.pollinations.ai — Kontext requires it now."
        )

    full_prompt = f"{scene_prompt}. Keep the same character identity, face, and clothing as the reference image."
    url = f"{GEN_BASE}/v1/images/edits"
    headers = {"Authorization": f"Bearer {api_key}"}
    data = {"prompt": full_prompt, "model": "kontext", "seed": str(seed)}
    files = {"image": ("reference.png", reference_image_bytes, "image/png")}

    last_err = None
    for attempt in range(retries):
        try:
            r = requests.post(url, headers=headers, data=data, files=files, timeout=120)
            r.raise_for_status()
            if r.headers.get("content-type", "").startswith("image"):
                return r.content
            raise ValueError(f"Unexpected content-type: {r.headers.get('content-type')}, body: {r.text[:300]}")
        except requests.exceptions.HTTPError as e:
            body = e.response.text[:500] if e.response is not None else ""
            last_err = f"{e} | response body: {body}"
            time.sleep(backoff * (attempt + 1))
        except Exception as e:
            last_err = e
            time.sleep(backoff * (attempt + 1))
    raise RuntimeError(f"Pollinations (Kontext) request failed after {retries} attempts: {last_err}")
